###
#   Database Settings
###


  ###
  #   H2 Settings && redis
  ###
spring:
  datasource:
    url: jdbc:h2:file:~/test5;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    pas sword:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  cache:
    type: redis
  redis:
    port: 6379
    host: localhost

server:
  port: 8444
